version: '3'

services:
    server:
        build: ./server
        expose:
            - 8000
        environment: 
            API_HOST: "http://localhost:3000/"
            APP_SERVER_PORT: 8000
        command: npm start
    
    client:
        build: ./client
        environment: 
            - REACT_APP_PORT=3000
        ports:
            - 3000:3000
        links:
            - server
        command: npm start

